name: Lint Workflow

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install grimagents cli and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Format with black
      run: |
        pip install black
        black -l 100 -S grimagents tests --check
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
